spring.application.name=mcp-agent
server.port=8082

spring.main.web-application-type=servlet

spring.ai.google.genai.api-key=${apiKey}
spring.ai.google.genai.chat.options.model=gemini-3.1-flash-lite-preview

spring.ai.mcp.client.enabled=false
spring.ai.mcp.client.sse.connections.mcp-tools-server.url=http://localhost:8083/sse

logging.level.io.modelcontextprotocol=TRACE
logging.level.org.springframework.ai.mcp=DEBUG