spring.application.name=mcp-agent

server.port=8082

spring.datasource.url=jdbc:postgresql://localhost:5432/agent_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=pguser
spring.datasource.password=${db.password}

spring.main.web-application-type=servlet

spring.ai.mcp.server.name=ai-mcp-agent
spring.ai.mcp.server.version=1.0.0

spring.ai.mcp.server.type=SYNC
spring.ai.mcp.server.streamable-http-endpoint=/stream

# LangChain4j Google AI Gemini Configuration
langchain4j.google-ai-gemini.chat-model.api-key=${apiKey}
langchain4j.google-ai-gemini.chat-model.model-name=gemini-2.5-flash-lite
langchain4j.google-ai-gemini.chat-model.temperature=0.7
langchain4j.google-ai-gemini.chat-model.max-tokens=1000
